/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    {
      type: 'doc',
      label: 'Introduction',
      id: 'intro',
    },
    {
      type: 'doc',
      label: 'Use Cases',
      id: 'use-cases',
    },
    {
      type: 'category',
      label: 'CLI',
      items: [
       'cli/getting-started',
       'cli/fetch-config-hcl',
       {
        type: 'category',
        label: 'Commands',
        items: [
          'cli/commands/completion',
          'cli/commands/fetch',
          'cli/commands/init',
          'cli/commands/options',
          'cli/commands/policy',
          'cli/commands/policy-download',
          'cli/commands/policy-run',
          'cli/commands/provider',
          'cli/commands/provider-download'
        ]
       },   
      ],
    },
    {
      type: 'category',
      label: 'Developers',
      items: ['developers/architecture', 'developers/debugging', 'developers/developing-new-provider'],
    },
    {
      type: 'doc',
      label: 'Best Practices',
      id: 'best-practices',
    },
    {
      type: 'doc',
      label: 'Security',
      id: 'security',
    },
    {
      type: 'doc',
      label: 'Troubleshooting',
      id: 'troubleshooting',
    },
    {
      type: 'doc',
      label: 'Videos & Blogs',
      id: 'videos-and-blogs',
    },
    {
      type: 'doc',
      label: 'Glossary',
      id: 'glossary',
    },
  ],
  
};
